### ISSUE TITLE
활동을 등록하는데 Unknown Exception이 발생함

### ISSUE THREAD

**Issue by enbraining** [GSM-MSG/SMS-BackEnd#284]
### Describe

활동(Authentication) 등록 요청을 보냈으나, 500 Internal Server Error 에러가 발생했고 해당 에러코드와 동일한 예외에는 User의 InternalServerError가 있었지만 이것에도 해당하지 않았습니다. 

**Test Program**: Insomnia
**URL**: localhost:8080/authentication
**Method**: POST

## Header
```
{
  "Content-Type": "application/json",
  "User-Agent": "insomnia/8.6.1",
  "Authorization": "Authorization ey..."
}
```

## Body
```
{
	"title": "블로그를 만들었어요~",
	"content": "블록블록~",
	"activityImages": [
		"https://cdn.pixabay.com/photo/2023/07/12/17/23/activity-8122959_1280.jpg"
	]
}
```

### Additional

프론트엔드 단에서 S3에 저장을 해서 백엔드로 버킷에서 URL을 주는 것인지 생각해보았으나 아닌 것 같았고, 모르겠어서 이슈로 남겼습니다.

<img width="1378" alt="Screenshot 2024-03-06 at 8 53 24 PM" src="https://github.com/GSM-MSG/SMS-BackEnd/assets/119437754/630b4b72-7d9f-411e-95d6-955de0eacc1d">

**Comment by ani2689** [comment]
![image](https://github.com/GSM-MSG/SMS-BackEnd/assets/106813267/890f794a-115b-4126-b182-39323c9aac94)
저는 잘 되는데, 한 번 짐작하자면 회원가입 후 학생 정보를 입력하지 않은 계정으로 요청한 것 같아요.

![image](https://github.com/GSM-MSG/SMS-BackEnd/assets/106813267/9be97850-805c-46a2-922b-c19cf8d68c1c)
아마 여기서 null이 들어와 터지는 것 같아요. null을 허용하고 서비스 단에서 null이라면 예외를 터트려주면 해결될 것 같아요~!

**Comment by enbraining** [comment]
그렇게 하는 게 좋을 것 같네요! 회원정보를 넣어준 것으로 알고 있었는데 안 들어갔나봐요 감사합니다~~
